version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - MrSpeedy35
      - TejasLamba2006
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
    allow:
      - dependency-type: "direct"
      - dependency-type: "development"
