# Cool Greetings Action
#
# This Action adds a touch of flair by sending friendly messages to users who open their
# first issue or pull request in the repository. Let's make the open-source journey exciting!
#
# Source repository: https://github.com/yourusername/your-repo
name: "Cool Greetings"

on:
  pull_request_target:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: "Check First Interaction"
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "🎉 Welcome to the open-source adventure! Thanks for opening your first issue in our repository. We're here to help! 🚀"
          pr-message: "👋 Hey there! Congratulations on your first pull request! 🎈 Your contributions are valued, and we're thrilled to have you on board! 🌟"
